language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
dist: xenial
addons:
  apt:
    packages:
      - kyototycoon
      - libkyototycoon-dev
services:
  - redis
install: "pip install gevent redis peewee ukt"
env: HUEY_TRAVIS=1
script: "python runtests.py"
notifications:
  email: true
